### ISSUE TITLE
Button to add sci-hub.cc suffix to domain

### ISSUE THREAD

**Issue by cossio** [arwankhoiruddin/scihubsearch#3]
I know this might not be the main intention of this plugin, but I found nowhere else to ask. You can see this as a feature request. For me it would be very convenient if we added a button to chrome, such that if I am currently viewing this paper:

http://www.mitpressjournals.org/doi/abs/10.1162/artl.2006.12.4.617?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub%3Dpubmed&

Clicking this button automatically redirects to:

http://www.mitpressjournals.org.sci-hub.cc/doi/abs/10.1162/artl.2006.12.4.617?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub%3Dpubmed&

(with an added sci-hub.cc suffix at the domain).

Would it be possible to add this feature to this extension? If the answer is not, would you suggest how I can accomplish this? Thanks.

**Comment by arwankhoiruddin** [comment]
Hi Jorge,

Interesting idea. Thank you very much. I am working on it.

Arwan Khoiruddin

**Comment by cossio** [comment]
Thanks. Note that adding a `http://sci-hub.cc/` prefix also works:

http://sci-hub.cc/http://www.mitpressjournals.org/doi/abs/10.1162/artl.2006.12.4.617?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub%3Dpubmed&

This may be simpler to do.

**Comment by arwankhoiruddin** [comment]
Hi Jorge,

Thank you for requesting this amazing feature. I am sorry for the late finishing. I have been very busy lately preparing for my proposal defense. 

I have updated the extension based on your request. If your extension does not update automatically, you may update this extension and enjoy it.

Please let me know if you satisfy with the update. Also please let me know if you have any other inputs in the future.

Cheers,
Arwan Khoiruddin

**Comment by arwankhoiruddin** [comment]
The changes have been pushed into the repository. Closing this ticket

**Comment by cossio** [comment]
Thanks! That's very nice of you. It works great.
