### ISSUE TITLE
a paper -> new tab

### ISSUE THREAD

**Issue by chalwanna** [arwankhoiruddin/scihubsearch#5]
Hi! Thank you for your awesome work. 
Is it possible to open a paper as in a new tab? When you're doing literature search at pubmed it's a little pain is 3letters when you need to come back and forth. Bests, A.

**Comment by arwankhoiruddin** [comment]
Hi @chalwanna Thank you for your comment. I will find the way to have two releases, one with "open new tab" and one with "open in the same tab".

**Comment by arwankhoiruddin** [comment]
@chalwanna Sorry for the delay. You can go to "newtab" branch and download the branch instead of the master one. Enjoy!

**Comment by chalwanna** [comment]
THANK YOU.

**Comment by cossio** [comment]
Is it possible to detect `Ctrl + Click` vs. `Click`? Then `Ctrl + Click` can be used to open in new tab, and `Click` to open in current tab.

**Comment by arwankhoiruddin** [comment]
@cossio nice idea. I create a new ticket so I don't forget #6
